// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductDosageApp.Data;

#nullable disable

namespace ProductDosageApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240910065813_AddProduktConfiguration")]
    partial class AddProduktConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductDosageApp.Models.Bestandteil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bestand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bestandteile");
                });

            modelBuilder.Entity("ProductDosageApp.Models.Dosage", b =>
                {
                    b.Property<int>("DosageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosageID"));

                    b.Property<string>("Dos1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dos9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DosageID");

                    b.ToTable("Dosages");
                });

            modelBuilder.Entity("ProductDosageApp.Models.DosageBestandteil", b =>
                {
                    b.Property<int>("DosageBestandteilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosageBestandteilID"));

                    b.Property<int>("BestandteilID")
                        .HasColumnType("int");

                    b.Property<int>("DosageID")
                        .HasColumnType("int");

                    b.HasKey("DosageBestandteilID");

                    b.HasIndex("BestandteilID");

                    b.HasIndex("DosageID");

                    b.ToTable("DosageBestandteile");
                });

            modelBuilder.Entity("ProductDosageApp.Models.Produkt", b =>
                {
                    b.Property<int>("ProduktID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktID"));

                    b.Property<int>("Anzahl")
                        .HasColumnType("int");

                    b.Property<string>("MKZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrapNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZVar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduktID");

                    b.ToTable("Produkts");
                });

            modelBuilder.Entity("ProductDosageApp.Models.ProduktDosage", b =>
                {
                    b.Property<int>("ProduktDosageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktDosageID"));

                    b.Property<int>("DosageID")
                        .HasColumnType("int");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.HasKey("ProduktDosageID");

                    b.HasIndex("DosageID");

                    b.HasIndex("ProduktID");

                    b.ToTable("ProduktDosages");
                });

            modelBuilder.Entity("ProduktConfiguration", b =>
                {
                    b.Property<int>("ProduktConfigurationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktConfigurationID"));

                    b.Property<int?>("Dos10BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos11BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos1BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos2BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos3BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos4BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos5BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos6BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos7BestandteilID")
                        .HasColumnType("int");

                    b.Property<int?>("Dos9BestandteilID")
                        .HasColumnType("int");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.HasKey("ProduktConfigurationID");

                    b.HasIndex("Dos10BestandteilID");

                    b.HasIndex("Dos11BestandteilID");

                    b.HasIndex("Dos1BestandteilID");

                    b.HasIndex("Dos2BestandteilID");

                    b.HasIndex("Dos3BestandteilID");

                    b.HasIndex("Dos4BestandteilID");

                    b.HasIndex("Dos5BestandteilID");

                    b.HasIndex("Dos6BestandteilID");

                    b.HasIndex("Dos7BestandteilID");

                    b.HasIndex("Dos9BestandteilID");

                    b.HasIndex("ProduktID");

                    b.ToTable("ProduktConfigurations");
                });

            modelBuilder.Entity("ProductDosageApp.Models.DosageBestandteil", b =>
                {
                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Bestandteil")
                        .WithMany()
                        .HasForeignKey("BestandteilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductDosageApp.Models.Dosage", "Dosage")
                        .WithMany("DosageBestandteile")
                        .HasForeignKey("DosageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestandteil");

                    b.Navigation("Dosage");
                });

            modelBuilder.Entity("ProductDosageApp.Models.ProduktDosage", b =>
                {
                    b.HasOne("ProductDosageApp.Models.Dosage", "Dosage")
                        .WithMany("ProduktDosages")
                        .HasForeignKey("DosageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductDosageApp.Models.Produkt", "Produkt")
                        .WithMany("ProduktDosages")
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosage");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("ProduktConfiguration", b =>
                {
                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos10Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos10BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos11Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos11BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos1Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos1BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos2Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos2BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos3Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos3BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos4Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos4BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos5Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos5BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos6Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos6BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos7Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos7BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Bestandteil", "Dos9Bestandteil")
                        .WithMany()
                        .HasForeignKey("Dos9BestandteilID");

                    b.HasOne("ProductDosageApp.Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dos10Bestandteil");

                    b.Navigation("Dos11Bestandteil");

                    b.Navigation("Dos1Bestandteil");

                    b.Navigation("Dos2Bestandteil");

                    b.Navigation("Dos3Bestandteil");

                    b.Navigation("Dos4Bestandteil");

                    b.Navigation("Dos5Bestandteil");

                    b.Navigation("Dos6Bestandteil");

                    b.Navigation("Dos7Bestandteil");

                    b.Navigation("Dos9Bestandteil");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("ProductDosageApp.Models.Dosage", b =>
                {
                    b.Navigation("DosageBestandteile");

                    b.Navigation("ProduktDosages");
                });

            modelBuilder.Entity("ProductDosageApp.Models.Produkt", b =>
                {
                    b.Navigation("ProduktDosages");
                });
#pragma warning restore 612, 618
        }
    }
}
